// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_merkle_airdrop`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-05-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Veronikas-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/resonance-runtime/resonance_runtime.wasm
// --pallet
// pallet-merkle-airdrop
// --extrinsic
// 
// --template
// ./.maintain/frame-weight-template.hbs
// --output
// ./pallets/merkle-airdrop/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_merkle_airdrop`.
pub trait WeightInfo {
	fn create_airdrop() -> Weight;
	fn fund_airdrop() -> Weight;
	fn claim() -> Weight;
	fn delete_airdrop() -> Weight;
}

/// Weights for `pallet_merkle_airdrop` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `MerkleAirdrop::NextAirdropId` (r:1 w:1)
	/// Proof: `MerkleAirdrop::NextAirdropId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropCreators` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropCreators` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1489`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:0)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn fund_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `3593`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:0)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::Claimed` (r:1 w:1)
	/// Proof: `MerkleAirdrop::Claimed` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3593`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropCreators` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropCreators` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn delete_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `341`
		//  Estimated: `3593`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `MerkleAirdrop::NextAirdropId` (r:1 w:1)
	/// Proof: `MerkleAirdrop::NextAirdropId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropCreators` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropCreators` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1489`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:0)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn fund_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `3593`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:0)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::Claimed` (r:1 w:1)
	/// Proof: `MerkleAirdrop::Claimed` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3593`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropMerkleRoots` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropMerkleRoots` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropCreators` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropCreators` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropBalances` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropBalances` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn delete_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `341`
		//  Estimated: `3593`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
