---
name: free disk space
description: when rust compiling, free up some disk space

runs:
  using: composite
  steps:
    - name: free disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 1.3.1
      with:
        android: true
        dotnet: false
        haskell: false
        large-packages: false
        swap-storage: false
